[project]
name = "ml-project-foundations"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
   
]

[dependency-groups]
dev = [
    "black>=25.12.0",
    "mypy>=1.19.1",
    "pytest>=9.0.2",
    "ruff>=0.14.11",
    "pre-commit>=4.5.1",
]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.mypy]
ignore_missing_imports = true
disallow_untyped_defs = false


[tool.ruff]
line-length = 120
target-version = "py312"
fix = true

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "I",  # isort (import sorting)
]
ignore = [
    "E501",  # line length (handled by black)
]

[tool.ruff.lint.isort]
known-first-party = ["ml_project_foundations"]

[tool.black]
line-length = 120
target-version = ["py312"]
