hydra:
  run:
    dir: .local/hydra/${experiment.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: .local/hydra/multirun/${experiment.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    chdir: true
