name: Run checks

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v6
        with:
          path: ML-project-foundations

      - name: Check out data quarry
        uses: actions/checkout@v6
        with:
          repository: johanbn89/ML-project-foundations-data-quarry
          path: ML-project-foundations-data-quarry

      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: ML-project-foundations/uv.lock

      - name: Sync environment
        working-directory: ML-project-foundations
        run: |
          uv sync --frozen --all-groups

      - name: Get Python and mypy versions
        shell: bash
        working-directory: ML-project-foundations
        run: |
          PY_VERSION=$(uv run python -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
          MYPY_VERSION=$(uv run mypy --version | awk '{print $2}')

          echo "PY_VERSION=$PY_VERSION" >> "$GITHUB_ENV"
          echo "MYPY_VERSION=$MYPY_VERSION" >> "$GITHUB_ENV"

      - name: Cache mypy
        uses: actions/cache@v4
        with:
          path: ML-project-foundations/.mypy_cache
          key: mypy-${{ runner.os }}-py${{ env.PY_VERSION }}-mypy${{ env.MYPY_VERSION }}
          restore-keys: |
            mypy-${{ runner.os }}-py${{ env.PY_VERSION }}-
            mypy-${{ runner.os }}-

      - name: Ruff
        working-directory: ML-project-foundations
        run: uv run ruff check .

      - name: Black
        working-directory: ML-project-foundations
        run: uv run black --check .

      - name: Mypy
        working-directory: ML-project-foundations
        run: uv run mypy src

      - name: Pytest
        working-directory: ML-project-foundations
        run: uv run pytest -v
